[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.20'
bytecode_hash = "none"
cbor_metadata = false
via_ir = true


[rpc_endpoints]
rpc_url = "${RPC_URL}"

[etherscan]
optimism_goerli_etherscan = { key = "${ETHERSCAN_L2_API_KEY}", chain = "sepolia" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
