[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
optimism_goerli = "${OPTIMISM_GOERLI_RPC_URL}"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
