[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
rpc_url = "${RPC_URL}"

[etherscan]
optimism_goerli_etherscan = { key = "${ETHERSCAN_L2_API_KEY}", chain = "goerli" }



# See more config options https://github.com/foundry-rs/foundry/tree/master/config
