name: Deployment (Dev)

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build, Test, and Deploy
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Cache Yarn files manually (extra resilience)
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Node Dependencies
        run: yarn install --frozen-lockfile --network-concurrency 5 --no-progress --verbose

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Run Forge Install Script
        run: chmod +x setup.sh && ./setup.sh

      - name: Run Forge Tests
        run: cd chain && forge test --summary

      - name: Run ESLint
        run: yarn lint:check

      - name: Check Formatting
        run: yarn format:check

      - name: Deploy
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.LIGHTSAIL_INSTANCE_PUBLIC_IP_DEV }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ETHERSCAN_L2_API_KEY: ${{ secrets.ETHERSCAN_L2_API_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RPC_URL: ${{ secrets.RPC_URL }}
        run: |
          DEPLOY_TIME=$(date +%s)
          echo "DEPLOY_TIME: $DEPLOY_TIME"

          echo "$SSH_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key

          DEPLOY_DIR="/tmp/deploy-${DEPLOY_TIME}"
          mkdir -p $DEPLOY_DIR

          echo "Preparing deployment files..."
          cp -r . $DEPLOY_DIR/

          echo "Syncing files to server..."
          rsync -az --dele
